//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID_BOL { get; set; }
        public Nullable<int> BOL_CODPAGO { get; set; }
        public Nullable<double> BOL_PRECTOTAL { get; set; }
        public int ID_COMP { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
    }
}
