//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTRADA()
        {
            this.TICKET = new HashSet<TICKET>();
        }
    
        public int ID_ENT { get; set; }
        public string EN_NOMBRE { get; set; }
        public Nullable<int> EN_CANT { get; set; }
        public Nullable<double> EN_PRECIO { get; set; }
        public string EN_DESC { get; set; }
        public Nullable<bool> EN_ACTIVADO { get; set; }
        public int ID_EVEN { get; set; }
        public int ID_CANTMIN { get; set; }
        public int ID_CANTMAX { get; set; }
        public int ID_CANTXUSU { get; set; }
        public int ID_FINVENTA { get; set; }
    
        public virtual CANTMAX CANTMAX { get; set; }
        public virtual CANTMIN CANTMIN { get; set; }
        public virtual CANTXUSU CANTXUSU { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        public virtual FINVENTA FINVENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
